### ISSUE TITLE
allow RHS with multiple columns

### ISSUE THREAD

**Issue by chriscoey** [RalphAS/IterativeRefinement.jl#1]
I'd love to be able to use this package but my `b` is a Matrix with a small number of columns (2 or 3)

**Comment by RalphAS** [comment]
I believe the linear solver now handles Matrix RHS correctly (in master).  Thanks for the suggestion, it prompted some related improvements.

**Comment by chriscoey** [comment]
Thank you so much! I'll try it out in the next week
